version: '3.9'

services:
  backend:
    container_name: swapi-backend
    build:
      context: ./
      dockerfile: star-wars-api/star-wars-api/Dockerfile
    ports:
      - "5198:8080"
    networks:
      - swapi-network

  frontend:
    container_name: swapi-frontend
    build:
      context: ./starships-frontend
      dockerfile: Dockerfile
    ports:
      - "4201:80"
    depends_on:
      - backend
    networks:
      - swapi-network

networks:
  swapi-network:
